# =========================
# Infrastructure
# =========================

[ansible]
ansible01 ansible_host=172.21.30.140

[monitoring]
monitor01 ansible_host=172.21.30.141

[cicd]
cicd01 ansible_host=172.21.30.142

[database]
mysql01 ansible_host=172.21.30.143

[cache]
redis01 ansible_host=172.21.30.144


# =========================
# Service Groups
# =========================

[prometheus]
monitor01

[loki]
monitor01

[jenkins]
cicd01

[mysql]
mysql01

[redis]
redis01


# =========================
# Business Groups
# =========================

[infra:children]
monitoring
cicd

[middleware:children]
mysql
redis

[all_servers:children]
infra
middleware